version: '3.1'
services:
  app:
    image: service-account
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa
      - POSTGRES_DB=service_account
